---
title: "Rating"
format: pdf
editor: visual
---

## Rating History

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(gghighlight)
library(lubridate)
library(plotly)
library(RColorBrewer)

raw_data <- read_xlsx("rating_tidy.xlsx", sheet = "tidy_data")

scale <- read_excel("rating_tidy.xlsx", sheet = "scale") 

#Moodys combined with score
rat_mood <-raw_data %>% filter(provider == "Moody's")
scale_mood <- scale %>% select(MOODYS, Score) %>% rename(rating = MOODYS)

moodys <- left_join(rat_mood, scale_mood)

#SP combined with score
rat_sp <-raw_data %>% filter(provider == "Standard & Poor's")
scale_sp <- scale %>% select(SP, Score) %>% rename(rating = SP)

sp <- left_join(rat_sp, scale_sp)

#Fitch combined with score
rat_fc <-raw_data %>% filter(provider == "Fitch")
scale_fc <- scale %>% select(Fitch, Score) %>% rename(rating = Fitch)

fc <- left_join(rat_fc, scale_fc)

#R&I combined with score
rat_ri <-raw_data %>% filter(provider == "Rating and Investment")
scale_ri <- scale %>% select('R&I', Score) %>% rename(rating = 'R&I')

ri <- left_join(rat_ri, scale_ri)

#JCRA combined with score
rat_jc <-raw_data %>% filter(provider == "Japan Credit Rating Agency")
scale_jc <- scale %>% select('JCRA', Score) %>% rename(rating = 'JCRA')

jc <- left_join(rat_jc, scale_jc)

#Combine all
combine(moodys, fc, sp, ri, jc)-> rating_all



```

```{r}
# Visualize

tiff("test.tiff", units="in", width=5, height=5, res=300)

rating_all %>%
ggplot(aes(x = date, y = Score, color = provider))+
  # annotate("rect", xmin = min(rating_all$date), xmax = max(rating_all$date), ymin = 11, ymax = Inf, fill = "lightblue")+
  #color area Investment grade
   # geom_rect(inherit.aes = F, xmin = 0, xmax = Inf, ymin = 11, ymax = Inf, fill = "lightblue", color = "transparent", alpha = 0.1)+
  
  scale_y_continuous(breaks=c(0, 5, 10, 13),
                     labels=c("C/SD", "B-", "BB+", "BBB+"))+
  geom_line(size = 1.4)+
  geom_point(size = 1.5)+
  geom_hline(yintercept = 11, linetype = "dashed")+
  gghighlight(provider == "Rating and Investment", unhighlighted_colour = "lightgrey", line_label_type = "ggrepel_label")+
  annotate("text", label ="INVESTMENT GRADE",  x = median(rating_all$date), y = 11.5)+
  ylab("Rating")+
  xlab("")+
  theme_classic()+
  theme(legend.position = "bottom") 


ggsave("rating_history.png", device='tiff', dpi=300, units = "px", limitsize = F)

  
  


```
